from PyQt5 import QtCore, QtGui, QtWidgets
from ConexaoBD import User


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 590)
        MainWindow.setStyleSheet("background-color: rgb(174, 142, 255);")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\Deyvid\\Desktop\\ArquivosUI\\../Repo-GitHub/ControllFinance/finance.png"))
        self.label.setObjectName("label")
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(190, 140, 181, 21))
        self.lineEdit_cpf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cpf.setText("")
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 40, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(25)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 410, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(190, 180, 181, 21))
        self.lineEdit_nome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_snome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_snome.setGeometry(QtCore.QRect(190, 220, 181, 21))
        self.lineEdit_snome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_snome.setText("")
        self.lineEdit_snome.setObjectName("lineEdit_snome")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setGeometry(QtCore.QRect(190, 410, 181, 21))
        self.lineEdit_senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_senha.setText("")
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.lineEdit_conf_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_conf_senha.setGeometry(QtCore.QRect(190, 460, 181, 21))
        self.lineEdit_conf_senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_conf_senha.setText("")
        self.lineEdit_conf_senha.setObjectName("lineEdit_conf_senha")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 360, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox_sexo = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sexo.setGeometry(QtCore.QRect(190, 370, 181, 21))
        self.comboBox_sexo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_sexo.setObjectName("comboBox_sexo")
        self.comboBox_sexo.addItem("")
        self.comboBox_sexo.addItem("")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 270, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(190, 270, 411, 21))
        self.lineEdit_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.dateEdit_nasc = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_nasc.setGeometry(QtCore.QRect(190, 320, 181, 22))
        self.dateEdit_nasc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit_nasc.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 4, 16), QtCore.QTime(0, 0, 0)))
        self.dateEdit_nasc.setObjectName("dateEdit_nasc")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 510, 51, 41))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Deyvid\\Desktop\\ArquivosUI\\../../Downloads/button(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "CPF:"))
        self.label_5.setText(_translate("MainWindow", "ControllFinance"))
        self.label_6.setText(_translate("MainWindow", "Primeiro Nome:"))
        self.label_7.setText(_translate("MainWindow", "Sobrenome:"))
        self.label_8.setText(_translate("MainWindow", "Data de Nascimento:"))
        self.label_9.setText(_translate("MainWindow", "Senha:"))
        self.label_10.setText(_translate("MainWindow", "Confirmar Senha:"))
        self.label_11.setText(_translate("MainWindow", "Sexo:"))
        self.comboBox_sexo.setItemText(0, _translate("MainWindow", "Masculino"))
        self.comboBox_sexo.setItemText(1, _translate("MainWindow", "Feminino"))
        self.label_12.setText(_translate("MainWindow", "E-mail:"))

        self.pushButton.clicked.connect(self.inserir_dados)

        # Lançamento dos dados para o banco na tabela Users
    def inserir_dados(self):
        cpf = self.lineEdit_cpf.text()
        nome = self.lineEdit_nome.text()
        sobrenome = self.lineEdit_snome.text()
        nomeCom = nome.ljust(7) + sobrenome
        email = self.lineEdit_email.text()
        sexo = self.comboBox_sexo.currentText()
        dataNasc = self.dateEdit_nasc.text()
        senha = self.lineEdit_senha.text()
        confSenh = self.lineEdit_conf_senha.text()
        c = confSenh


        while len(confSenh) <= len(senha) or len(confSenh) >= len(senha):
            if confSenh == senha:
                ins = User().inserir(cpf,nomeCom,email,sexo,dataNasc,senha)
                return ins

            elif confSenh != senha:
                print('A confirmação da senha está diferente da senha. DIGITE NOVAMENTE:')
                self.lineEdit_conf_senha.clear()
                break





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
